version: 2.1

executors:
  php-executor:
    docker:
      - image: cimg/php:8.2
    working_directory: ~/Laravel-app

orbs:
  php: circleci/php@1.0
jobs:
  build:
    executor: php-executor
    # docker:
    #   - image: cimg/php:8.2-browsers # Use a CircleCI PHP image with browsers for Dusk testing
    steps:
      - checkout
      - run:
          name: "Install Laravel dependencies"
          command: |
            composer install
          
      # Set up the Laravel application
      - run:
          name: "Setup Laravel"
          command: |
            cp .env.example .env
            php artisan key:generate
      
      # Lint code.
      - run:
          name: "Lint codebase."
          command: |
            git config --global user.email "ci-bot@example.com"
            git config --global user.name "CircleCI Bot"
            ./vendor/bin/pint
      - run:
          name: Commit & Push Fixes
          command: |
            if [ -n "$(git status --porcelain)" ]; then
              git add .
              git commit --amend --no-edit
              git push origin HEAD --force
            else
              echo "No Pint fixes needed"
            fi

  test:
    docker:
      - image: cimg/php:8.2
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
    working_directory: ~/Laravel-app
    steps:
      - checkout
      - run:
          name: Copy Environment
          command: cp .env.example .env
      - run:
          name: Generate Key
          command: php artisan key:generate
      - run:
          name: Run Migrations
          command: php artisan migrate --force
      - run:
          name: Run PHPUnit Tests
          command: vendor/bin/phpunit
            
workflows:
  version: 2
  main_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
