version: 2.1

executors:
  php-executor:
    docker:
      - image: cimg/php:8.2
    working_directory: ~/Laravel-app

orbs:
  php: circleci/php@1.0
jobs:
  build_and_test:
    executor: php-executor
    # docker:
    #   - image: cimg/php:8.2-browsers # Use a CircleCI PHP image with browsers for Dusk testing
    steps:
      - checkout
      - run:
          name: "Install Laravel dependencies"
          command: |
            composer install
          
      # Set up the Laravel application
      - run:
          name: "Setup Laravel"
          command: |
            cp .env.example .env
            php artisan key:generate
      
      # Lint code.
      - run:
          name: "Lint codebase."
          command: |
            ./vendor/bin/pint
            
      # Run tests
      - run:
          name: "Run PHPUnit tests"
          command: |
            ./vendor/bin/phpunit
            
workflows:
  version: 2
  main_workflow:
    jobs:
      - build_and_test

