version: 2.1
orbs:
  php: circleci/php@1.0
jobs:
  build_and_test:
    docker:
      - image: cimg/php:8.2-browsers # Use a CircleCI PHP image with browsers for Dusk testing
      - image: cimg/mysql:5.7 # Use a MySQL service container for database tests
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
          MYSQL_USER: root
          MYSQL_PASSWORD: root
    
    environment:
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_DATABASE: laravel_test
      DB_USERNAME: root
      DB_PASSWORD: root

    steps:
      - checkout
      
      - run:
          name: "Install php extensions dependencies"
          command: |
            sudo docker-php-ext-install pdo pdo_mysql
      
      - run:
          name: "Install Laravel dependencies"
          command: |
            composer install
          
      # Set up the Laravel application
      - run:
          name: "Setup Laravel"
          command: |
            cp .env.example .env
            php artisan key:generate
            php artisan migrate --force
            
      # Run tests
      - run:
          name: "Run PHPUnit tests"
          command: |
            ./vendor/bin/phpunit
            
workflows:
  main_workflow:
    jobs:
      - build_and_test
